Don't minify CSS
When minifying CSS, we're using libsass, which errors because of an
incompatibility:

```
error  build/stylesheets/screen-old-ie.css
Error: "calc(0px)" is not a number for `max'
on line 1775 of stdin, in function `max`
from line 1775 of stdin
>>   @supports (margin: max(calc(0px))) {
---------------------^
```

When libsass is updated, we can minify the CSS again
(https://github.com/alphagov/tech-docs-gem/pull/89#issuecomment-51315607
5).