Update to rubocop-govuk 3.5.0
This should fix these errors seen on CI and locally:

> rubocop example lib spec Rakefile
> /home/travis/.rvm/gems/ruby-2.6.3/gems/rubocop-govuk-1.0.0/config/gds-ruby-styleguide.yml: Metrics/LineLength has the wrong namespace - should be Layout
> Error: The `Layout/AlignArray` cop has been renamed to `Layout/ArrayAlignment`.
> (obsolete configuration found in /home/travis/.rvm/gems/ruby-2.6.3/gems/rubocop-govuk-1.0.0/config/gds-ruby-styleguide.yml, please update it)
> The `Layout/Tab` cop has been renamed to `Layout/IndentationStyle`.
> (obsolete configuration found in /home/travis/.rvm/gems/ruby-2.6.3/gems/rubocop-govuk-1.0.0/config/gds-ruby-styleguide.yml, please update it)
> The `Layout/TrailingBlankLines` cop has been renamed to `Layout/TrailingEmptyLines`.
> (obsolete configuration found in /home/travis/.rvm/gems/ruby-2.6.3/gems/rubocop-govuk-1.0.0/config/gds-ruby-styleguide.yml, please update it)
> The `Lint/StringConversionInInterpolation` cop has been renamed to `Lint/RedundantStringCoercion`.
> (obsolete configuration found in /home/travis/.rvm/gems/ruby-2.6.3/gems/rubocop-govuk-1.0.0/config/gds-ruby-styleguide.yml, please update it)
> obsolete parameter Whitelist (for Style/TrivialAccessors) found in /home/travis/.rvm/gems/ruby-2.6.3/gems/rubocop-govuk-1.0.0/config/gds-ruby-styleguide.yml
> `Whitelist` has been renamed to `AllowedMethods`.